spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sortify
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: sortify
